// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3_SLcXxQV1RQhmMnzZqnpVJ8R9ot7e0',
    appId: '1:525871661809:web:6cd6fd4b635cf75b0b1f50',
    messagingSenderId: '525871661809',
    projectId: 'fineartshop-56190',
    authDomain: 'fineartshop-56190.firebaseapp.com',
    databaseURL: 'https://fineartshop-56190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fineartshop-56190.appspot.com',
    measurementId: 'G-9C4RV97NZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpLK3aQdp9X6DvDjdcvAeN8prdjcx6TDQ',
    appId: '1:525871661809:android:54c0d35d5637ef590b1f50',
    messagingSenderId: '525871661809',
    projectId: 'fineartshop-56190',
    databaseURL: 'https://fineartshop-56190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fineartshop-56190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtEAQWuhwUsuM_bag1vaMEEfZpRP1ICg',
    appId: '1:525871661809:ios:29d4d95bbfbc4dc90b1f50',
    messagingSenderId: '525871661809',
    projectId: 'fineartshop-56190',
    databaseURL: 'https://fineartshop-56190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fineartshop-56190.appspot.com',
    androidClientId: '525871661809-n3t1lde01cjlqsa25c7jhmm8ks80ee8i.apps.googleusercontent.com',
    iosClientId: '525871661809-hprvk7suh0j0u9j347lsde3qj7jlbfcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fineArtShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtEAQWuhwUsuM_bag1vaMEEfZpRP1ICg',
    appId: '1:525871661809:ios:29d4d95bbfbc4dc90b1f50',
    messagingSenderId: '525871661809',
    projectId: 'fineartshop-56190',
    databaseURL: 'https://fineartshop-56190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fineartshop-56190.appspot.com',
    androidClientId: '525871661809-n3t1lde01cjlqsa25c7jhmm8ks80ee8i.apps.googleusercontent.com',
    iosClientId: '525871661809-hprvk7suh0j0u9j347lsde3qj7jlbfcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fineArtShop',
  );
}
